server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
          - id: dummy
            uri: lb://dummy #lb - load-balancing
            predicates:
              - Path=/api/dummy/**
            filters:
              - RewritePath=/api/dummy/(?<remaining>.*), /${remaining}
    loadbalancer:
      ribbon:
        enabled: false
