# Name of the Application
spring:
  zipkin:
    baseUrl: http://tracing-server:9411
  application:
    name: hellodoctor-auth
      
# Port of the Server
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${DNS_DISCOVERY_SERVER}:8761/eureka/

# mapper file
mybatis:
  config-location: classpath:mapper.xml
