# Name of the Application
spring:
  zipkin:
    baseUrl: http://tracing-server:9411
  application:
    name: hellodoctor-api-gateway
    
# Port of the Server
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: ongame.vn
    key-password: 12345
    key-store: classpath:ssl-key.p12
    key-store-type: PKCS12
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${DNS_DISCOVERY_SERVER}:8761/eureka/
        
zuul:
  prefix: /api
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    hellodoctor-api-gateway: /gateway/**
    hellodoctor-test-service: /test/**
    hellodoctor-auth: /auth/**
    hellodoctor-auth2: /auth2/**
    hellodoctor-location-service: /location/**
    hellodoctor-booking-service: /booking/**
    hellodoctor-account-service: /account/**

ribbon:
  ReadTimeout: 5000