# Name of the Application
spring:
  zipkin:
    baseUrl: http://tracing-server:9411
  application:
    name: hellodoctor-location-service

# Port of the Server
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${DNS_DISCOVERY_SERVER}:8761/eureka/


# Redis
redis:
  host: redis-server
  port: 6379
  password:
  timeout: 5000
  max-active: 200
  min-idle: 50
  max-idle: 50
  max-wait: 3000




