# Name of the Application
spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: hellodoctor-push-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/grabdoctor?useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

# Port of the Server
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/

logging:
  level:
    com:
      hellodoctor:
        booking:
          repository: DEBUG
