# Name of the Application
spring:
  zipkin:
    baseUrl: http://tracing-server:9411
  application:
    name: hellodoctor-api-gateway
    
# Port of the Server
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${DNS_DISCOVERY_SERVER}:8761/eureka/
