# Name of the Application
spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: hellodoctor-admin-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql:replication://35.247.128.219:3306,35.240.223.89:3306/grabdoctor?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

# Port of the Server
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/

location-service:
  url: http://localhost:8080/api/location
push-service:
  url: http://localhost:8080/api/push

logging:
  level:
    com:
      hellodoctor:
        booking:
          repository: DEBUG
