# Name of the Application
spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: hellodoctor-auth
  h2:
  console:
    enabled: true
    
    
security:
  basic:
    enabled: false
# Port of the Server
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/

# mapper file
mybatis:
  config-location: classpath:mapper.xml
