# Name of the Application
spring:
  zipkin:
    baseUrl: http://tracing-server:9411
  application:
    name: hellodoctor-storage-service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

# Port of the Server
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${DNS_DISCOVERY_SERVER}:8761/eureka/


